#ifndef CONSTANT_H_INCLUDED
#define CONSTANT_H_INCLUDED

const int SCREEN_WIDTH = 800;
const int SCREEN_HEIGHT = 600;
const int TILE_SIZE = 40;
const int MAP_WIDTH = SCREEN_WIDTH / TILE_SIZE; // 20
const int MAP_HEIGHT = SCREEN_HEIGHT / TILE_SIZE; // 15

#endif // CONSTANT_H_INCLUDED
